<?php

use Illuminate\Database\Seeder;

class YosralSettingsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('settings')->delete();
        
        \DB::table('settings')->insert(array (
            0 => 
            array (
                'id' => 1,
                'created_at' => '2021-07-13 03:42:37',
                'updated_at' => '2021-09-23 19:16:37',
                'user_id' => 1,
                'per_page' => 20,
                'site_name' => 'SIMPATI',
                'qr_code' => NULL,
                'qr_text' => NULL,
                'display_asset_name' => NULL,
                'display_checkout_date' => NULL,
                'display_eol' => NULL,
                'auto_increment_assets' => 1,
                'auto_increment_prefix' => NULL,
                'load_remote' => 1,
                'logo' => 'setting-logo-a4Mdr28q2Z.png',
                'header_color' => NULL,
                'alert_email' => 'dayanti.kharisma@gmail.com',
                'alerts_enabled' => 1,
                'default_eula_text' => 'default eula',
                'barcode_type' => 'QRCODE',
                'slack_endpoint' => NULL,
                'slack_channel' => NULL,
                'slack_botname' => NULL,
                'default_currency' => 'IDR',
                'custom_css' => NULL,
                'brand' => 1,
                'ldap_enabled' => NULL,
                'ldap_server' => NULL,
                'ldap_uname' => NULL,
                'ldap_pword' => NULL,
                'ldap_basedn' => NULL,
                'ldap_filter' => NULL,
                'ldap_username_field' => 'samaccountname',
                'ldap_lname_field' => 'sn',
                'ldap_fname_field' => 'givenname',
                'ldap_auth_filter_query' => 'uid=samaccountname',
                'ldap_version' => 3,
                'ldap_active_flag' => NULL,
                'ldap_dept' => NULL,
                'ldap_emp_num' => NULL,
                'ldap_email' => NULL,
                'ldap_phone_field' => NULL,
                'ldap_jobtitle' => NULL,
                'ldap_country' => NULL,
                'full_multiple_companies_support' => 1,
                'ldap_server_cert_ignore' => 0,
                'locale' => 'id',
                'labels_per_page' => 30,
                'labels_width' => '2.62500',
                'labels_height' => '1.00000',
                'labels_pmargin_left' => '0.21975',
                'labels_pmargin_right' => '0.21975',
                'labels_pmargin_top' => '0.50000',
                'labels_pmargin_bottom' => '0.50000',
                'labels_display_bgutter' => '0.07000',
                'labels_display_sgutter' => '0.05000',
                'labels_fontsize' => 9,
                'labels_pagewidth' => '8.50000',
                'labels_pageheight' => '11.00000',
                'labels_display_name' => 0,
                'labels_display_serial' => 1,
                'labels_display_tag' => 1,
                'alt_barcode' => 'C128',
                'alt_barcode_enabled' => 1,
                'alert_interval' => 30,
                'alert_threshold' => 5,
                'email_domain' => 'gmail.com',
                'email_format' => 'firstname.lastname',
                'username_format' => 'filastname',
                'is_ad' => 0,
                'ad_domain' => NULL,
                'ldap_port' => '389',
                'ldap_tls' => 0,
                'zerofill_count' => 5,
                'ldap_pw_sync' => 1,
                'two_factor_enabled' => NULL,
                'require_accept_signature' => 0,
                'date_display_format' => 'M j, Y',
                'time_display_format' => 'H:i',
                'next_auto_tag_base' => 4,
                'login_note' => NULL,
                'thumbnail_max_h' => 50,
                'pwd_secure_uncommon' => 0,
                'pwd_secure_complexity' => NULL,
                'pwd_secure_min' => 10,
                'audit_interval' => NULL,
                'audit_warning_days' => NULL,
                'show_url_in_emails' => 0,
                'custom_forgot_pass_url' => NULL,
                'show_alerts_in_menu' => 1,
                'labels_display_company_name' => 0,
                'show_archived_in_list' => 0,
                'dashboard_message' => NULL,
                'support_footer' => 'on',
                'footer_text' => NULL,
                'modellist_displays' => 'image,category,manufacturer,model_number',
                'login_remote_user_enabled' => 0,
                'login_common_disabled' => 0,
                'login_remote_user_custom_logout_url' => '',
                'skin' => 'blue',
                'show_images_in_email' => 1,
                'admin_cc_email' => NULL,
                'labels_display_model' => 0,
                'privacy_policy_link' => NULL,
                'version_footer' => 'on',
                'unique_serial' => 0,
                'logo_print_assets' => 0,
                'depreciation_method' => 'default',
                'favicon' => 'favicon-uploaded.ico',
                'email_logo' => NULL,
                'label_logo' => NULL,
                'allow_user_skin' => 0,
                'show_assigned_assets' => 0,
                'login_remote_user_header_name' => '',
                'ad_append_domain' => 0,
                'saml_enabled' => 0,
                'saml_idp_metadata' => NULL,
                'saml_attr_mapping_username' => NULL,
                'saml_forcelogin' => 0,
                'saml_slo' => 0,
                'saml_sp_x509cert' => NULL,
                'saml_sp_privatekey' => NULL,
                'saml_custom_settings' => NULL,
                'saml_sp_x509certNew' => NULL,
                'digit_separator' => '1.234,56',
            ),
        ));
        
        
    }
}