<?php

use Illuminate\Database\Seeder;

class YosralActionLogsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('action_logs')->delete();
        
        \DB::table('action_logs')->insert(array (
            0 => 
            array (
                'id' => 1,
                'user_id' => 1,
                'action_type' => 'create',
                'target_id' => NULL,
                'target_type' => NULL,
                'location_id' => NULL,
                'note' => NULL,
                'filename' => NULL,
                'item_type' => 'App\\Models\\Asset',
                'item_id' => 1,
                'expected_checkin' => NULL,
                'accepted_id' => NULL,
                'created_at' => '2021-08-24 08:16:48',
                'updated_at' => '2021-08-24 08:16:48',
                'deleted_at' => NULL,
                'thread_id' => NULL,
                'company_id' => NULL,
                'accept_signature' => NULL,
                'log_meta' => NULL,
                'action_date' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'user_id' => 1,
                'action_type' => 'update',
                'target_id' => NULL,
                'target_type' => NULL,
                'location_id' => NULL,
                'note' => NULL,
                'filename' => NULL,
                'item_type' => 'App\\Models\\Asset',
                'item_id' => 1,
                'expected_checkin' => NULL,
                'accepted_id' => NULL,
                'created_at' => '2021-08-24 08:18:52',
                'updated_at' => '2021-08-24 08:18:52',
                'deleted_at' => NULL,
                'thread_id' => NULL,
                'company_id' => NULL,
                'accept_signature' => NULL,
                'log_meta' => '{"name":{"old":null,"new":"Laptop PTI"}}',
                'action_date' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'user_id' => 1,
                'action_type' => 'update',
                'target_id' => NULL,
                'target_type' => NULL,
                'location_id' => NULL,
                'note' => NULL,
                'filename' => NULL,
                'item_type' => 'App\\Models\\Asset',
                'item_id' => 1,
                'expected_checkin' => NULL,
                'accepted_id' => NULL,
                'created_at' => '2021-08-24 08:48:45',
                'updated_at' => '2021-08-24 08:48:45',
                'deleted_at' => NULL,
                'thread_id' => NULL,
                'company_id' => NULL,
                'accept_signature' => NULL,
                'log_meta' => '{"purchase_date":{"old":null,"new":"2021-08-24"},"purchase_cost":{"old":null,"new":12000000},"warranty_months":{"old":null,"new":"12"}}',
                'action_date' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'user_id' => 1,
                'action_type' => 'create',
                'target_id' => NULL,
                'target_type' => NULL,
                'location_id' => NULL,
                'note' => NULL,
                'filename' => NULL,
                'item_type' => 'App\\Models\\Asset',
                'item_id' => 2,
                'expected_checkin' => NULL,
                'accepted_id' => NULL,
                'created_at' => '2021-08-25 12:40:31',
                'updated_at' => '2021-08-25 12:40:31',
                'deleted_at' => NULL,
                'thread_id' => NULL,
                'company_id' => NULL,
                'accept_signature' => NULL,
                'log_meta' => NULL,
                'action_date' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'user_id' => 1,
                'action_type' => 'update',
                'target_id' => NULL,
                'target_type' => NULL,
                'location_id' => NULL,
                'note' => NULL,
                'filename' => NULL,
                'item_type' => 'App\\Models\\Asset',
                'item_id' => 2,
                'expected_checkin' => NULL,
                'accepted_id' => NULL,
                'created_at' => '2021-08-25 12:41:44',
                'updated_at' => '2021-08-25 12:41:44',
                'deleted_at' => NULL,
                'thread_id' => NULL,
                'company_id' => NULL,
                'accept_signature' => NULL,
                'log_meta' => '{"status_id":{"old":3,"new":"2"}}',
                'action_date' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'user_id' => 1,
                'action_type' => 'delete',
                'target_id' => NULL,
                'target_type' => NULL,
                'location_id' => NULL,
                'note' => NULL,
                'filename' => NULL,
                'item_type' => 'App\\Models\\Asset',
                'item_id' => 2,
                'expected_checkin' => NULL,
                'accepted_id' => NULL,
                'created_at' => '2021-08-25 12:42:03',
                'updated_at' => '2021-08-25 12:42:03',
                'deleted_at' => NULL,
                'thread_id' => NULL,
                'company_id' => NULL,
                'accept_signature' => NULL,
                'log_meta' => NULL,
                'action_date' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'user_id' => 1,
                'action_type' => 'add seats',
                'target_id' => NULL,
                'target_type' => NULL,
                'location_id' => NULL,
                'note' => 'added 2 seats',
                'filename' => NULL,
                'item_type' => 'App\\Models\\License',
                'item_id' => 1,
                'expected_checkin' => NULL,
                'accepted_id' => NULL,
                'created_at' => '2021-09-01 20:54:27',
                'updated_at' => '2021-09-01 20:54:27',
                'deleted_at' => NULL,
                'thread_id' => NULL,
                'company_id' => NULL,
                'accept_signature' => NULL,
                'log_meta' => NULL,
                'action_date' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'user_id' => 1,
                'action_type' => 'create',
                'target_id' => NULL,
                'target_type' => NULL,
                'location_id' => NULL,
                'note' => NULL,
                'filename' => NULL,
                'item_type' => 'App\\Models\\License',
                'item_id' => 1,
                'expected_checkin' => NULL,
                'accepted_id' => NULL,
                'created_at' => '2021-09-01 20:54:28',
                'updated_at' => '2021-09-01 20:54:28',
                'deleted_at' => NULL,
                'thread_id' => NULL,
                'company_id' => NULL,
                'accept_signature' => NULL,
                'log_meta' => NULL,
                'action_date' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'user_id' => 1,
                'action_type' => 'delete seats',
                'target_id' => NULL,
                'target_type' => NULL,
                'location_id' => NULL,
                'note' => 'deleted 1 seats',
                'filename' => NULL,
                'item_type' => 'App\\Models\\License',
                'item_id' => 1,
                'expected_checkin' => NULL,
                'accepted_id' => NULL,
                'created_at' => '2021-09-15 15:05:24',
                'updated_at' => '2021-09-15 15:05:24',
                'deleted_at' => NULL,
                'thread_id' => NULL,
                'company_id' => NULL,
                'accept_signature' => NULL,
                'log_meta' => NULL,
                'action_date' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'user_id' => 1,
                'action_type' => 'update',
                'target_id' => NULL,
                'target_type' => NULL,
                'location_id' => NULL,
                'note' => NULL,
                'filename' => NULL,
                'item_type' => 'App\\Models\\License',
                'item_id' => 1,
                'expected_checkin' => NULL,
                'accepted_id' => NULL,
                'created_at' => '2021-09-15 15:05:25',
                'updated_at' => '2021-09-15 15:05:25',
                'deleted_at' => NULL,
                'thread_id' => NULL,
                'company_id' => NULL,
                'accept_signature' => NULL,
                'log_meta' => NULL,
                'action_date' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'user_id' => 1,
                'action_type' => 'update',
                'target_id' => NULL,
                'target_type' => NULL,
                'location_id' => NULL,
                'note' => NULL,
                'filename' => NULL,
                'item_type' => 'App\\Models\\Asset',
                'item_id' => 1,
                'expected_checkin' => NULL,
                'accepted_id' => NULL,
                'created_at' => '2021-09-16 15:00:41',
                'updated_at' => '2021-09-16 15:00:41',
                'deleted_at' => NULL,
                'thread_id' => NULL,
                'company_id' => NULL,
                'accept_signature' => NULL,
                'log_meta' => '{"order_number":{"old":null,"new":"10"},"supplier_id":{"old":null,"new":"1"},"company_id":{"old":null,"new":"1"}}',
                'action_date' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'user_id' => 1,
                'action_type' => 'checkout',
                'target_id' => 2,
                'target_type' => 'App\\Models\\User',
                'location_id' => NULL,
                'note' => '',
                'filename' => NULL,
                'item_type' => 'App\\Models\\Asset',
                'item_id' => 1,
                'expected_checkin' => NULL,
                'accepted_id' => NULL,
                'created_at' => '2021-09-16 15:02:09',
                'updated_at' => '2021-09-16 15:02:09',
                'deleted_at' => NULL,
                'thread_id' => NULL,
                'company_id' => NULL,
                'accept_signature' => NULL,
                'log_meta' => NULL,
                'action_date' => '2021-09-16 15:02:08',
            ),
            12 => 
            array (
                'id' => 13,
                'user_id' => 1,
                'action_type' => 'checkout',
                'target_id' => 1,
                'target_type' => 'App\\Models\\Asset',
                'location_id' => NULL,
                'note' => NULL,
                'filename' => NULL,
                'item_type' => 'App\\Models\\License',
                'item_id' => 1,
                'expected_checkin' => NULL,
                'accepted_id' => NULL,
                'created_at' => '2021-09-16 15:16:28',
                'updated_at' => '2021-09-16 15:16:28',
                'deleted_at' => NULL,
                'thread_id' => NULL,
                'company_id' => 1,
                'accept_signature' => NULL,
                'log_meta' => NULL,
                'action_date' => '2021-09-16 15:16:28',
            ),
            13 => 
            array (
                'id' => 14,
                'user_id' => 1,
                'action_type' => 'add seats',
                'target_id' => NULL,
                'target_type' => NULL,
                'location_id' => NULL,
                'note' => 'added 1 seats',
                'filename' => NULL,
                'item_type' => 'App\\Models\\License',
                'item_id' => 1,
                'expected_checkin' => NULL,
                'accepted_id' => NULL,
                'created_at' => '2021-09-16 15:17:03',
                'updated_at' => '2021-09-16 15:17:03',
                'deleted_at' => NULL,
                'thread_id' => NULL,
                'company_id' => NULL,
                'accept_signature' => NULL,
                'log_meta' => NULL,
                'action_date' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'user_id' => 1,
                'action_type' => 'update',
                'target_id' => NULL,
                'target_type' => NULL,
                'location_id' => NULL,
                'note' => NULL,
                'filename' => NULL,
                'item_type' => 'App\\Models\\License',
                'item_id' => 1,
                'expected_checkin' => NULL,
                'accepted_id' => NULL,
                'created_at' => '2021-09-16 15:17:03',
                'updated_at' => '2021-09-16 15:17:03',
                'deleted_at' => NULL,
                'thread_id' => NULL,
                'company_id' => NULL,
                'accept_signature' => NULL,
                'log_meta' => NULL,
                'action_date' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'user_id' => 1,
                'action_type' => 'checkout',
                'target_id' => 1,
                'target_type' => 'App\\Models\\User',
                'location_id' => NULL,
                'note' => NULL,
                'filename' => NULL,
                'item_type' => 'App\\Models\\License',
                'item_id' => 1,
                'expected_checkin' => NULL,
                'accepted_id' => NULL,
                'created_at' => '2021-09-16 15:18:22',
                'updated_at' => '2021-09-16 15:18:22',
                'deleted_at' => NULL,
                'thread_id' => NULL,
                'company_id' => NULL,
                'accept_signature' => NULL,
                'log_meta' => NULL,
                'action_date' => '2021-09-16 15:18:22',
            ),
            16 => 
            array (
                'id' => 17,
                'user_id' => 1,
                'action_type' => 'checkin from',
                'target_id' => 1,
                'target_type' => 'App\\Models\\User',
                'location_id' => NULL,
                'note' => NULL,
                'filename' => NULL,
                'item_type' => 'App\\Models\\License',
                'item_id' => 1,
                'expected_checkin' => NULL,
                'accepted_id' => NULL,
                'created_at' => '2021-09-16 15:19:02',
                'updated_at' => '2021-09-16 15:19:02',
                'deleted_at' => NULL,
                'thread_id' => NULL,
                'company_id' => NULL,
                'accept_signature' => NULL,
                'log_meta' => NULL,
                'action_date' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'user_id' => 1,
                'action_type' => 'checkout',
                'target_id' => 2,
                'target_type' => 'App\\Models\\User',
                'location_id' => NULL,
                'note' => NULL,
                'filename' => NULL,
                'item_type' => 'App\\Models\\License',
                'item_id' => 1,
                'expected_checkin' => NULL,
                'accepted_id' => NULL,
                'created_at' => '2021-09-18 14:45:09',
                'updated_at' => '2021-09-18 14:45:09',
                'deleted_at' => NULL,
                'thread_id' => NULL,
                'company_id' => 3,
                'accept_signature' => NULL,
                'log_meta' => NULL,
                'action_date' => '2021-09-18 14:45:09',
            ),
            18 => 
            array (
                'id' => 19,
                'user_id' => 1,
                'action_type' => 'update',
                'target_id' => NULL,
                'target_type' => NULL,
                'location_id' => NULL,
                'note' => NULL,
                'filename' => NULL,
                'item_type' => 'App\\Models\\License',
                'item_id' => 1,
                'expected_checkin' => NULL,
                'accepted_id' => NULL,
                'created_at' => '2021-09-18 14:52:57',
                'updated_at' => '2021-09-18 14:52:57',
                'deleted_at' => NULL,
                'thread_id' => NULL,
                'company_id' => 3,
                'accept_signature' => NULL,
                'log_meta' => NULL,
                'action_date' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'user_id' => 1,
                'action_type' => 'checkin from',
                'target_id' => 2,
                'target_type' => 'App\\Models\\User',
                'location_id' => NULL,
                'note' => NULL,
                'filename' => NULL,
                'item_type' => 'App\\Models\\License',
                'item_id' => 1,
                'expected_checkin' => NULL,
                'accepted_id' => NULL,
                'created_at' => '2021-09-18 14:54:02',
                'updated_at' => '2021-09-18 14:54:02',
                'deleted_at' => NULL,
                'thread_id' => NULL,
                'company_id' => 3,
                'accept_signature' => NULL,
                'log_meta' => NULL,
                'action_date' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'user_id' => 2,
                'action_type' => 'create',
                'target_id' => NULL,
                'target_type' => NULL,
                'location_id' => NULL,
                'note' => NULL,
                'filename' => NULL,
                'item_type' => 'App\\Models\\Asset',
                'item_id' => 3,
                'expected_checkin' => NULL,
                'accepted_id' => NULL,
                'created_at' => '2021-09-18 14:57:06',
                'updated_at' => '2021-09-18 14:57:06',
                'deleted_at' => NULL,
                'thread_id' => NULL,
                'company_id' => 3,
                'accept_signature' => NULL,
                'log_meta' => NULL,
                'action_date' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'user_id' => 1,
                'action_type' => 'update',
                'target_id' => NULL,
                'target_type' => NULL,
                'location_id' => NULL,
                'note' => NULL,
                'filename' => NULL,
                'item_type' => 'App\\Models\\License',
                'item_id' => 1,
                'expected_checkin' => NULL,
                'accepted_id' => NULL,
                'created_at' => '2021-09-18 21:12:31',
                'updated_at' => '2021-09-18 21:12:31',
                'deleted_at' => NULL,
                'thread_id' => NULL,
                'company_id' => 3,
                'accept_signature' => NULL,
                'log_meta' => NULL,
                'action_date' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'user_id' => 1,
                'action_type' => 'update',
                'target_id' => NULL,
                'target_type' => NULL,
                'location_id' => NULL,
                'note' => NULL,
                'filename' => NULL,
                'item_type' => 'App\\Models\\License',
                'item_id' => 1,
                'expected_checkin' => NULL,
                'accepted_id' => NULL,
                'created_at' => '2021-09-18 21:25:58',
                'updated_at' => '2021-09-18 21:25:58',
                'deleted_at' => NULL,
                'thread_id' => NULL,
                'company_id' => 3,
                'accept_signature' => NULL,
                'log_meta' => NULL,
                'action_date' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'user_id' => 1,
                'action_type' => 'update',
                'target_id' => NULL,
                'target_type' => NULL,
                'location_id' => NULL,
                'note' => NULL,
                'filename' => NULL,
                'item_type' => 'App\\Models\\License',
                'item_id' => 1,
                'expected_checkin' => NULL,
                'accepted_id' => NULL,
                'created_at' => '2021-09-18 21:26:38',
                'updated_at' => '2021-09-18 21:26:38',
                'deleted_at' => NULL,
                'thread_id' => NULL,
                'company_id' => 3,
                'accept_signature' => NULL,
                'log_meta' => NULL,
                'action_date' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'user_id' => 1,
                'action_type' => 'update',
                'target_id' => NULL,
                'target_type' => NULL,
                'location_id' => NULL,
                'note' => NULL,
                'filename' => NULL,
                'item_type' => 'App\\Models\\License',
                'item_id' => 1,
                'expected_checkin' => NULL,
                'accepted_id' => NULL,
                'created_at' => '2021-09-18 21:29:02',
                'updated_at' => '2021-09-18 21:29:02',
                'deleted_at' => NULL,
                'thread_id' => NULL,
                'company_id' => 3,
                'accept_signature' => NULL,
                'log_meta' => NULL,
                'action_date' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'user_id' => 1,
                'action_type' => 'update',
                'target_id' => NULL,
                'target_type' => NULL,
                'location_id' => NULL,
                'note' => NULL,
                'filename' => NULL,
                'item_type' => 'App\\Models\\License',
                'item_id' => 1,
                'expected_checkin' => NULL,
                'accepted_id' => NULL,
                'created_at' => '2021-09-18 21:29:33',
                'updated_at' => '2021-09-18 21:29:33',
                'deleted_at' => NULL,
                'thread_id' => NULL,
                'company_id' => 3,
                'accept_signature' => NULL,
                'log_meta' => NULL,
                'action_date' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'user_id' => 1,
                'action_type' => 'update',
                'target_id' => NULL,
                'target_type' => NULL,
                'location_id' => NULL,
                'note' => NULL,
                'filename' => NULL,
                'item_type' => 'App\\Models\\License',
                'item_id' => 1,
                'expected_checkin' => NULL,
                'accepted_id' => NULL,
                'created_at' => '2021-09-19 00:00:58',
                'updated_at' => '2021-09-19 00:00:58',
                'deleted_at' => NULL,
                'thread_id' => NULL,
                'company_id' => 3,
                'accept_signature' => NULL,
                'log_meta' => NULL,
                'action_date' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'user_id' => 1,
                'action_type' => 'update',
                'target_id' => NULL,
                'target_type' => NULL,
                'location_id' => NULL,
                'note' => NULL,
                'filename' => NULL,
                'item_type' => 'App\\Models\\Asset',
                'item_id' => 1,
                'expected_checkin' => NULL,
                'accepted_id' => NULL,
                'created_at' => '2021-09-19 18:36:20',
                'updated_at' => '2021-09-19 18:36:20',
                'deleted_at' => NULL,
                'thread_id' => NULL,
                'company_id' => 1,
                'accept_signature' => NULL,
                'log_meta' => '{"bmn":{"old":null,"new":"3100102003-3688"},"serial":{"old":null,"new":"C02VK2LWHH25"},"expected_checkin":{"old":"2021-11-30","new":"2021-11-30 00:00:00"}}',
                'action_date' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'user_id' => 1,
                'action_type' => 'update',
                'target_id' => NULL,
                'target_type' => NULL,
                'location_id' => NULL,
                'note' => NULL,
                'filename' => NULL,
                'item_type' => 'App\\Models\\Asset',
                'item_id' => 1,
                'expected_checkin' => NULL,
                'accepted_id' => NULL,
                'created_at' => '2021-09-19 18:41:48',
                'updated_at' => '2021-09-19 18:41:48',
                'deleted_at' => NULL,
                'thread_id' => NULL,
                'company_id' => 1,
                'accept_signature' => NULL,
                'log_meta' => '{"order_number":{"old":"10","new":null},"expected_checkin":{"old":"2021-11-30","new":"2021-11-30 00:00:00"}}',
                'action_date' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'user_id' => 1,
                'action_type' => 'update',
                'target_id' => NULL,
                'target_type' => NULL,
                'location_id' => NULL,
                'note' => NULL,
                'filename' => NULL,
                'item_type' => 'App\\Models\\Asset',
                'item_id' => 3,
                'expected_checkin' => NULL,
                'accepted_id' => NULL,
                'created_at' => '2021-09-22 17:17:14',
                'updated_at' => '2021-09-22 17:17:14',
                'deleted_at' => NULL,
                'thread_id' => NULL,
                'company_id' => 3,
                'accept_signature' => NULL,
                'log_meta' => '{"status_id":{"old":2,"new":"1"}}',
                'action_date' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'user_id' => 1,
                'action_type' => 'update',
                'target_id' => NULL,
                'target_type' => NULL,
                'location_id' => NULL,
                'note' => NULL,
                'filename' => NULL,
                'item_type' => 'App\\Models\\Asset',
                'item_id' => 3,
                'expected_checkin' => NULL,
                'accepted_id' => NULL,
                'created_at' => '2021-09-22 19:07:08',
                'updated_at' => '2021-09-22 19:07:09',
                'deleted_at' => NULL,
                'thread_id' => NULL,
                'company_id' => 3,
                'accept_signature' => NULL,
                'log_meta' => '{"status_id":{"old":1,"new":"2"}}',
                'action_date' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'user_id' => 1,
                'action_type' => 'checkin from',
                'target_id' => 2,
                'target_type' => 'App\\Models\\User',
                'location_id' => NULL,
                'note' => NULL,
                'filename' => NULL,
                'item_type' => 'App\\Models\\Asset',
                'item_id' => 1,
                'expected_checkin' => NULL,
                'accepted_id' => NULL,
                'created_at' => '2021-09-22 19:08:12',
                'updated_at' => '2021-09-22 19:08:12',
                'deleted_at' => NULL,
                'thread_id' => NULL,
                'company_id' => 3,
                'accept_signature' => NULL,
                'log_meta' => NULL,
                'action_date' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'user_id' => 1,
                'action_type' => 'checkout',
                'target_id' => 2,
                'target_type' => 'App\\Models\\User',
                'location_id' => NULL,
                'note' => '',
                'filename' => NULL,
                'item_type' => 'App\\Models\\Asset',
                'item_id' => 1,
                'expected_checkin' => NULL,
                'accepted_id' => NULL,
                'created_at' => '2021-09-22 19:09:14',
                'updated_at' => '2021-09-22 19:09:14',
                'deleted_at' => NULL,
                'thread_id' => NULL,
                'company_id' => 3,
                'accept_signature' => NULL,
                'log_meta' => NULL,
                'action_date' => '2021-09-22 19:09:14',
            ),
            33 => 
            array (
                'id' => 34,
                'user_id' => 1,
                'action_type' => 'checkin from',
                'target_id' => 2,
                'target_type' => 'App\\Models\\User',
                'location_id' => NULL,
                'note' => NULL,
                'filename' => NULL,
                'item_type' => 'App\\Models\\Asset',
                'item_id' => 1,
                'expected_checkin' => NULL,
                'accepted_id' => NULL,
                'created_at' => '2021-09-22 19:11:04',
                'updated_at' => '2021-09-22 19:11:04',
                'deleted_at' => NULL,
                'thread_id' => NULL,
                'company_id' => 3,
                'accept_signature' => NULL,
                'log_meta' => NULL,
                'action_date' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'user_id' => 1,
                'action_type' => 'checkout',
                'target_id' => 2,
                'target_type' => 'App\\Models\\User',
                'location_id' => NULL,
                'note' => '',
                'filename' => NULL,
                'item_type' => 'App\\Models\\Asset',
                'item_id' => 1,
                'expected_checkin' => NULL,
                'accepted_id' => NULL,
                'created_at' => '2021-09-22 19:11:20',
                'updated_at' => '2021-09-22 19:11:20',
                'deleted_at' => NULL,
                'thread_id' => NULL,
                'company_id' => 3,
                'accept_signature' => NULL,
                'log_meta' => NULL,
                'action_date' => '2021-09-22 19:11:19',
            ),
            35 => 
            array (
                'id' => 36,
                'user_id' => 1,
                'action_type' => 'checkout',
                'target_id' => 3,
                'target_type' => 'App\\Models\\Asset',
                'location_id' => NULL,
                'note' => NULL,
                'filename' => NULL,
                'item_type' => 'App\\Models\\License',
                'item_id' => 1,
                'expected_checkin' => NULL,
                'accepted_id' => NULL,
                'created_at' => '2021-09-22 19:20:09',
                'updated_at' => '2021-09-22 19:20:09',
                'deleted_at' => NULL,
                'thread_id' => NULL,
                'company_id' => 3,
                'accept_signature' => NULL,
                'log_meta' => NULL,
                'action_date' => '2021-09-22 19:20:09',
            ),
            36 => 
            array (
                'id' => 37,
                'user_id' => 1,
                'action_type' => 'update',
                'target_id' => NULL,
                'target_type' => NULL,
                'location_id' => NULL,
                'note' => NULL,
                'filename' => NULL,
                'item_type' => 'App\\Models\\License',
                'item_id' => 1,
                'expected_checkin' => NULL,
                'accepted_id' => NULL,
                'created_at' => '2021-09-22 19:33:04',
                'updated_at' => '2021-09-22 19:33:04',
                'deleted_at' => NULL,
                'thread_id' => NULL,
                'company_id' => 3,
                'accept_signature' => NULL,
                'log_meta' => NULL,
                'action_date' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'user_id' => 1,
                'action_type' => 'update',
                'target_id' => NULL,
                'target_type' => NULL,
                'location_id' => NULL,
                'note' => NULL,
                'filename' => NULL,
                'item_type' => 'App\\Models\\Asset',
                'item_id' => 3,
                'expected_checkin' => NULL,
                'accepted_id' => NULL,
                'created_at' => '2021-09-23 22:03:11',
                'updated_at' => '2021-09-23 22:03:11',
                'deleted_at' => NULL,
                'thread_id' => NULL,
                'company_id' => 3,
                'accept_signature' => NULL,
                'log_meta' => '{"bmn":{"old":null,"new":"3100102003-3680"}}',
                'action_date' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'user_id' => 1,
                'action_type' => 'update',
                'target_id' => NULL,
                'target_type' => NULL,
                'location_id' => NULL,
                'note' => NULL,
                'filename' => NULL,
                'item_type' => 'App\\Models\\Asset',
                'item_id' => 3,
                'expected_checkin' => NULL,
                'accepted_id' => NULL,
                'created_at' => '2021-09-23 23:19:16',
                'updated_at' => '2021-09-23 23:19:16',
                'deleted_at' => NULL,
                'thread_id' => NULL,
                'company_id' => 3,
                'accept_signature' => NULL,
                'log_meta' => '{"status_id":{"old":2,"new":"1"}}',
                'action_date' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'user_id' => 1,
                'action_type' => 'update',
                'target_id' => NULL,
                'target_type' => NULL,
                'location_id' => NULL,
                'note' => NULL,
                'filename' => NULL,
                'item_type' => 'App\\Models\\Asset',
                'item_id' => 3,
                'expected_checkin' => NULL,
                'accepted_id' => NULL,
                'created_at' => '2021-09-24 15:32:43',
                'updated_at' => '2021-09-24 15:32:43',
                'deleted_at' => NULL,
                'thread_id' => NULL,
                'company_id' => 3,
                'accept_signature' => NULL,
                'log_meta' => '{"status_id":{"old":1,"new":"2"}}',
                'action_date' => NULL,
            ),
        ));
        
        
    }
}