<?php

use Illuminate\Database\Seeder;

class YosralUsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'id' => 1,
                'email' => 'dayanti.kharisma@gmail.com',
                'password' => '$2y$10$.Y2lSCkk1YZ8Eo7QuZCeW.s3ay5MHvqzBE5CSMqcSmwAin8ccvBwC',
                'permissions' => '{"superuser":"1","admin":"0","import":"0","reports.view":"0","assets.view":"0","assets.create":"0","assets.edit":"0","assets.delete":"0","assets.checkin":"0","assets.checkout":"0","assets.audit":"0","assets.view.requestable":"0","accessories.view":"0","accessories.create":"0","accessories.edit":"0","accessories.delete":"0","accessories.checkout":"0","accessories.checkin":"0","consumables.view":"0","consumables.create":"0","consumables.edit":"0","consumables.delete":"0","consumables.checkout":"0","licenses.view":"0","licenses.create":"0","licenses.edit":"0","licenses.delete":"0","licenses.checkout":"0","licenses.keys":"0","licenses.files":"0","components.view":"0","components.create":"0","components.edit":"0","components.delete":"0","components.checkout":"0","components.checkin":"0","kits.view":"0","kits.create":"0","kits.edit":"0","kits.delete":"0","kits.checkout":"0","users.view":"0","users.create":"0","users.edit":"0","users.delete":"0","models.view":"0","models.create":"0","models.edit":"0","models.delete":"0","categories.view":"0","categories.create":"0","categories.edit":"0","categories.delete":"0","departments.view":"0","departments.create":"0","departments.edit":"0","departments.delete":"0","statuslabels.view":"0","statuslabels.create":"0","statuslabels.edit":"0","statuslabels.delete":"0","customfields.view":"0","customfields.create":"0","customfields.edit":"0","customfields.delete":"0","suppliers.view":"0","suppliers.create":"0","suppliers.edit":"0","suppliers.delete":"0","manufacturers.view":"0","manufacturers.create":"0","manufacturers.edit":"0","manufacturers.delete":"0","depreciations.view":"0","depreciations.create":"0","depreciations.edit":"0","depreciations.delete":"0","locations.view":"0","locations.create":"0","locations.edit":"0","locations.delete":"0","companies.view":"0","companies.create":"0","companies.edit":"0","companies.delete":"0","self.two_factor":"0","self.api":"0","self.edit_location":"0","self.checkout_assets":"0"}',
                'activated' => 1,
                'activation_code' => NULL,
                'activated_at' => NULL,
                'last_login' => '2021-11-15 14:10:29',
                'persist_code' => NULL,
                'reset_password_code' => NULL,
                'first_name' => 'Dayanti Kharisma Nur Amalia',
                'last_name' => NULL,
                'created_at' => '2021-07-13 03:42:37',
                'updated_at' => '2021-11-15 14:10:29',
                'deleted_at' => NULL,
                'website' => NULL,
                'country' => NULL,
                'gravatar' => NULL,
                'location_id' => NULL,
                'phone' => NULL,
                'jobtitle' => NULL,
                'manager_id' => NULL,
                'employee_num' => '340060041',
                'nip_baru' => '199901082021042001',
                'avatar' => NULL,
                'username' => 'admin',
                'notes' => NULL,
                'company_id' => NULL,
                'remember_token' => 'Y7oMLWQcZkBZrRXmDoEMyvy2FEGPyUAeQ5D0SL4vhpBs4RSM6R4MmVjAqxPm',
                'ldap_import' => 0,
                'locale' => 'id',
                'show_in_list' => 1,
                'two_factor_secret' => NULL,
                'two_factor_enrolled' => 0,
                'two_factor_optin' => 0,
                'department_id' => NULL,
                'address' => NULL,
                'city' => NULL,
                'state' => NULL,
                'zip' => NULL,
                'skin' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'email' => NULL,
                'password' => '$2y$10$3IqD4NjuNvywj7s.QMy/Qey3iXdRsGYJhKe61GuTIGW4KF.vzpTJa',
                'permissions' => 'null',
                'activated' => 1,
                'activation_code' => NULL,
                'activated_at' => NULL,
                'last_login' => '2021-10-29 12:44:16',
                'persist_code' => NULL,
                'reset_password_code' => NULL,
                'first_name' => 'Dew Kharisma',
                'last_name' => NULL,
                'created_at' => '2021-08-27 05:19:23',
                'updated_at' => '2021-10-29 12:44:16',
                'deleted_at' => NULL,
                'website' => NULL,
                'country' => NULL,
                'gravatar' => NULL,
                'location_id' => NULL,
                'phone' => NULL,
                'jobtitle' => NULL,
                'manager_id' => NULL,
                'employee_num' => '340060059',
                'nip_baru' => '200007202021042001',
                'avatar' => NULL,
                'username' => 'dekha',
                'notes' => NULL,
                'company_id' => 3,
                'remember_token' => NULL,
                'ldap_import' => 0,
                'locale' => 'id',
                'show_in_list' => 1,
                'two_factor_secret' => NULL,
                'two_factor_enrolled' => 0,
                'two_factor_optin' => 0,
                'department_id' => 3,
                'address' => NULL,
                'city' => NULL,
                'state' => NULL,
                'zip' => NULL,
                'skin' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'email' => NULL,
                'password' => '$2y$10$DiBpmzwht8illyVDDGE9i.LDdVuQiou4mLuYLjpasuvCxOVXDB7Be',
                'permissions' => 'null',
                'activated' => 1,
                'activation_code' => NULL,
                'activated_at' => NULL,
                'last_login' => '2021-09-24 19:14:58',
                'persist_code' => NULL,
                'reset_password_code' => NULL,
                'first_name' => 'Duta',
                'last_name' => NULL,
                'created_at' => '2021-09-22 21:27:05',
                'updated_at' => '2021-10-29 11:41:21',
                'deleted_at' => NULL,
                'website' => NULL,
                'country' => NULL,
                'gravatar' => NULL,
                'location_id' => NULL,
                'phone' => NULL,
                'jobtitle' => NULL,
                'manager_id' => NULL,
                'employee_num' => '340060050',
                'nip_baru' => NULL,
                'avatar' => NULL,
                'username' => 'dutakha',
                'notes' => NULL,
                'company_id' => 3,
                'remember_token' => NULL,
                'ldap_import' => 0,
                'locale' => 'id',
                'show_in_list' => 1,
                'two_factor_secret' => NULL,
                'two_factor_enrolled' => 0,
                'two_factor_optin' => 0,
                'department_id' => 3,
                'address' => NULL,
                'city' => NULL,
                'state' => NULL,
                'zip' => NULL,
                'skin' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'email' => NULL,
                'password' => '$2y$10$dNNdXGfIW0MvayxDlfMaRO4ruscR8kg9Hd0hBtyoxu2PlZ/I5bmwa',
                'permissions' => 'null',
                'activated' => 1,
                'activation_code' => NULL,
                'activated_at' => NULL,
                'last_login' => '2021-10-29 13:00:49',
                'persist_code' => NULL,
                'reset_password_code' => NULL,
                'first_name' => 'user coba',
                'last_name' => NULL,
                'created_at' => '2021-09-22 22:39:53',
                'updated_at' => '2021-10-29 13:00:49',
                'deleted_at' => NULL,
                'website' => NULL,
                'country' => NULL,
                'gravatar' => NULL,
                'location_id' => NULL,
                'phone' => NULL,
                'jobtitle' => NULL,
                'manager_id' => NULL,
                'employee_num' => NULL,
                'nip_baru' => NULL,
                'avatar' => NULL,
                'username' => 'usercoba',
                'notes' => NULL,
                'company_id' => 1,
                'remember_token' => NULL,
                'ldap_import' => 0,
                'locale' => NULL,
                'show_in_list' => 1,
                'two_factor_secret' => NULL,
                'two_factor_enrolled' => 0,
                'two_factor_optin' => 0,
                'department_id' => 1,
                'address' => NULL,
                'city' => NULL,
                'state' => NULL,
                'zip' => NULL,
                'skin' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'email' => 'yosral@bps.go.id',
                'password' => '$2a$10$/NP59PxqYuKoPT8eclUqx.2ok5BWoDYQNwJMC27gXWQmp51l0a04i',
                'permissions' => '{"superuser":"1","admin":"0","import":"0","reports.view":"0","assets.view":"0","assets.create":"0","assets.edit":"0","assets.delete":"0","assets.checkin":"0","assets.checkout":"0","assets.audit":"0","assets.view.requestable":"0","accessories.view":"0","accessories.create":"0","accessories.edit":"0","accessories.delete":"0","accessories.checkout":"0","accessories.checkin":"0","consumables.view":"0","consumables.create":"0","consumables.edit":"0","consumables.delete":"0","consumables.checkout":"0","licenses.view":"0","licenses.create":"0","licenses.edit":"0","licenses.delete":"0","licenses.checkout":"0","licenses.keys":"0","licenses.files":"0","components.view":"0","components.create":"0","components.edit":"0","components.delete":"0","components.checkout":"0","components.checkin":"0","kits.view":"0","kits.create":"0","kits.edit":"0","kits.delete":"0","kits.checkout":"0","users.view":"0","users.create":"0","users.edit":"0","users.delete":"0","models.view":"0","models.create":"0","models.edit":"0","models.delete":"0","categories.view":"0","categories.create":"0","categories.edit":"0","categories.delete":"0","departments.view":"0","departments.create":"0","departments.edit":"0","departments.delete":"0","statuslabels.view":"0","statuslabels.create":"0","statuslabels.edit":"0","statuslabels.delete":"0","customfields.view":"0","customfields.create":"0","customfields.edit":"0","customfields.delete":"0","suppliers.view":"0","suppliers.create":"0","suppliers.edit":"0","suppliers.delete":"0","manufacturers.view":"0","manufacturers.create":"0","manufacturers.edit":"0","manufacturers.delete":"0","depreciations.view":"0","depreciations.create":"0","depreciations.edit":"0","depreciations.delete":"0","locations.view":"0","locations.create":"0","locations.edit":"0","locations.delete":"0","companies.view":"0","companies.create":"0","companies.edit":"0","companies.delete":"0","self.two_factor":"0","self.api":"0","self.edit_location":"0","self.checkout_assets":"0"}',
                'activated' => 1,
                'activation_code' => NULL,
                'activated_at' => NULL,
                'last_login' => '2021-11-15 14:10:29',
                'persist_code' => NULL,
                'reset_password_code' => NULL,
                'first_name' => 'Rihan',
                'last_name' => 'Yosral',
                'created_at' => '2021-07-13 03:42:37',
                'updated_at' => '2021-11-15 14:10:29',
                'deleted_at' => NULL,
                'website' => NULL,
                'country' => NULL,
                'gravatar' => NULL,
                'location_id' => NULL,
                'phone' => NULL,
                'jobtitle' => NULL,
                'manager_id' => NULL,
                'employee_num' => '340058946',
                'nip_baru' => '199608022019011002',
                'avatar' => NULL,
                'username' => 'yosral',
                'notes' => NULL,
                'company_id' => NULL,
                'remember_token' => NULL,
                'ldap_import' => 0,
                'locale' => 'id',
                'show_in_list' => 1,
                'two_factor_secret' => NULL,
                'two_factor_enrolled' => 0,
                'two_factor_optin' => 0,
                'department_id' => NULL,
                'address' => NULL,
                'city' => NULL,
                'state' => NULL,
                'zip' => NULL,
                'skin' => NULL,
            ),
        ));
        
        
    }
}